[project]
name = "medsite2"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "django>=5.2.2",
    "django-phonenumber-field[phonenumberslite]>=8.1.0",
    "pillow>=11.2.1",
    "psycopg2>=2.9.10",
]
