# Generated by Django 5.2.2 on 2025-06-25 16:40

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Examination",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "examination_type",
                    models.CharField(
                        choices=[
                            ("ultrasound", "УЗИ"),
                            ("mri", "МРТ"),
                            ("ct", "КТ"),
                            ("xray", "Рентген"),
                        ],
                        max_length=20,
                        verbose_name="Тип исследования",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="например: сердца, ОБП",
                        max_length=100,
                        verbose_name="Область исследования",
                    ),
                ),
                (
                    "examination_date",
                    models.DateField(
                        default=django.utils.timezone.now,
                        verbose_name="Дата проведения",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        upload_to="examinations/{instance.result.examination.patient.user.id}/%Y/{filename}",
                        verbose_name="Изображение",
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="заметки",
                        verbose_name="Примечания",
                    ),
                ),
            ],
            options={
                "verbose_name": "Инструментальное исследование",
                "verbose_name_plural": "Инструментальные исследования",
                "ordering": ["patient", "name", "-examination_date"],
            },
        ),
        migrations.CreateModel(
            name="LaboratoryTest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "test_type",
                    models.CharField(
                        choices=[
                            ("biochemical-blood", "Биохимия крови"),
                            ("complete-blood-count", "Общий анализ крови"),
                            ("general-urine-analysis", "Общий анализ мочи"),
                        ],
                        default="biochemical-blood",
                        max_length=30,
                        verbose_name="Вид анализа",
                    ),
                ),
                ("examination_date", models.DateField(verbose_name="Дата проведения")),
            ],
            options={
                "verbose_name": "Группа лабораторного анализа",
                "verbose_name_plural": "Группа лабораторных анализов",
                "ordering": ["patient", "-examination_date"],
            },
        ),
        migrations.CreateModel(
            name="TestParameter",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Параметр")),
                ("value", models.CharField(max_length=10, verbose_name="Значение")),
                (
                    "unit",
                    models.CharField(
                        blank=True, max_length=30, verbose_name="Единицы измерения"
                    ),
                ),
                (
                    "normal_range",
                    models.CharField(
                        blank=True, max_length=30, verbose_name="Референсные значения"
                    ),
                ),
                (
                    "is_normal",
                    models.BooleanField(default=True, verbose_name="В норме"),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True, default="", verbose_name="Комментарии"
                    ),
                ),
            ],
            options={
                "verbose_name": "Параметр анализа, значения",
                "verbose_name_plural": "Параметры анализов, значения",
                "ordering": ["name"],
            },
        ),
    ]
