# Generated by Django 5.2.2 on 2025-06-06 17:38

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Group",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=250)),
            ],
            options={
                "verbose_name": "Группа анализов",
                "verbose_name_plural": "Группы анализов",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="TestName",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=250)),
                (
                    "group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="med_base.group"
                    ),
                ),
            ],
            options={
                "verbose_name": "Название анализа",
                "verbose_name_plural": "Название анализов",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Test",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("value", models.DecimalField(decimal_places=3, max_digits=9)),
                (
                    "upper_limit",
                    models.DecimalField(
                        blank=True, decimal_places=3, max_digits=9, null=True
                    ),
                ),
                (
                    "down_limit",
                    models.DecimalField(
                        blank=True, decimal_places=3, max_digits=9, null=True
                    ),
                ),
                ("date", models.DateField(default=django.utils.timezone.now)),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "name",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="med_base.testname",
                    ),
                ),
            ],
            options={
                "verbose_name": "Анализ",
                "verbose_name_plural": "Анализы",
                "ordering": ["name", "-date"],
            },
        ),
    ]
