# Generated by Django 5.2.2 on 2025-06-25 03:20

import django.db.models.deletion
import med_base.models
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AnalysisResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "laboratory",
                    models.CharField(
                        blank=True, max_length=30, verbose_name="Лаборатория"
                    ),
                ),
            ],
            options={
                "verbose_name": "Результат анализа",
                "verbose_name_plural": "Результаты анализов",
            },
        ),
        migrations.CreateModel(
            name="DiagnosticResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "protocol",
                    models.TextField(
                        blank=True, default="", verbose_name="Текстовый протокол"
                    ),
                ),
                (
                    "conclusion",
                    models.TextField(blank=True, default="", verbose_name="Заключение"),
                ),
            ],
            options={
                "verbose_name": "Результат диагностики",
                "verbose_name_plural": "Результаты диагностики",
            },
        ),
        migrations.CreateModel(
            name="Examination",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "examination_type",
                    models.CharField(
                        choices=[
                            ("analysis", "Лабораторный анализ"),
                            ("diagnostic", "Диагностическое исследование"),
                        ],
                        default="analysis",
                        max_length=20,
                        verbose_name="Тип исследования",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=100, verbose_name="Название исследования"
                    ),
                ),
                (
                    "examination_date",
                    models.DateTimeField(verbose_name="Дата проведения"),
                ),
                (
                    "notes",
                    models.TextField(blank=True, default="", verbose_name="Примечания"),
                ),
            ],
            options={
                "verbose_name": "Исследование",
                "verbose_name_plural": "Исследования",
                "ordering": ["-examination_date"],
            },
        ),
        migrations.CreateModel(
            name="HealthIndicator",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "indicator_type",
                    models.CharField(
                        help_text="Например: Артериальное давление, Вес",
                        max_length=100,
                        verbose_name="Тип показателя",
                    ),
                ),
                ("value", models.FloatField(verbose_name="Значение")),
                ("date_recorded", models.DateTimeField(verbose_name="Дата измерения")),
                (
                    "notes",
                    models.TextField(blank=True, default="", verbose_name="Примечания"),
                ),
            ],
            options={
                "verbose_name": "Медицинский показатель",
                "verbose_name_plural": "Медицинские показатели",
                "ordering": ["-date_recorded"],
            },
        ),
        migrations.CreateModel(
            name="AnalysisParameter",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Параметр")),
                ("value", models.CharField(max_length=10, verbose_name="Значение")),
                (
                    "unit",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="Единицы измерения"
                    ),
                ),
                (
                    "normal_range",
                    models.CharField(
                        blank=True, max_length=30, verbose_name="Референсные значения"
                    ),
                ),
                (
                    "is_normal",
                    models.BooleanField(default=True, verbose_name="В норме"),
                ),
                (
                    "result",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="parameters",
                        to="med_base.analysisresult",
                        verbose_name="Результат анализа",
                    ),
                ),
            ],
            options={
                "verbose_name": "Параметр анализа",
                "verbose_name_plural": "Параметры анализов",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="DiagnosticImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        upload_to=med_base.models.DiagnosticImage.upload_to_path,
                        verbose_name="Изображение",
                    ),
                ),
                (
                    "result",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="med_base.diagnosticresult",
                        verbose_name="Результат исследования",
                    ),
                ),
            ],
            options={
                "verbose_name": "Изображение исследования",
                "verbose_name_plural": "Изображения исследований",
            },
        ),
    ]
