# Generated by Django 5.2.2 on 2025-06-25 03:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("med_base", "0001_initial"),
        ("patients", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="examination",
            name="patient",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="examinations",
                to="patients.patient",
                verbose_name="Пациент",
            ),
        ),
        migrations.AddField(
            model_name="diagnosticresult",
            name="examination",
            field=models.OneToOneField(
                limit_choices_to={"examination_type": "diagnostic"},
                on_delete=django.db.models.deletion.CASCADE,
                related_name="diagnostic_result",
                to="med_base.examination",
                verbose_name="Исследование",
            ),
        ),
        migrations.AddField(
            model_name="analysisresult",
            name="examination",
            field=models.OneToOneField(
                limit_choices_to={"examination_type": "analysis"},
                on_delete=django.db.models.deletion.CASCADE,
                related_name="analysis_result",
                to="med_base.examination",
                verbose_name="Исследование",
            ),
        ),
        migrations.AddField(
            model_name="healthindicator",
            name="patient",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="health_indicators",
                to="patients.patient",
            ),
        ),
        migrations.AddIndex(
            model_name="examination",
            index=models.Index(
                fields=["examination_type"], name="med_base_ex_examina_f10061_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="examination",
            index=models.Index(
                fields=["examination_date"], name="med_base_ex_examina_cf14b4_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="healthindicator",
            index=models.Index(
                fields=["indicator_type"], name="med_base_he_indicat_4004e1_idx"
            ),
        ),
    ]
