# Generated by Django 5.2.2 on 2025-06-25 16:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("med_base", "0001_initial"),
        ("patients", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="examination",
            name="patient",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="examinations",
                to="patients.patient",
                verbose_name="Пациент",
            ),
        ),
        migrations.AddField(
            model_name="laboratorytest",
            name="patient",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="laboratory_tests",
                to="patients.patient",
                verbose_name="Пациент",
            ),
        ),
        migrations.AddField(
            model_name="testparameter",
            name="test",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="parameters",
                to="med_base.laboratorytest",
                verbose_name="Группа анализов",
            ),
        ),
        migrations.AddIndex(
            model_name="examination",
            index=models.Index(
                fields=["examination_date"], name="med_base_ex_examina_cf14b4_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="examination",
            index=models.Index(
                fields=["patient", "examination_type"],
                name="med_base_ex_patient_34a4ac_idx",
            ),
        ),
    ]
